google/chicago-brick

server/server.js
server/util/credentials.js
server/util/googleapis.js

This allows for users to put creds wherever they want, no longer needing to
modify chicago-brick to get this behavior.
This fixes #15.

Added credentials module.

---

client/modules/module_manager.js
lib/eval.js
package.json
server/modules/module_defs.js

Replace with a custom safeEval script, which does a better job of handling
line number failures, which makes debugging modules far easier.
Fixes #21.

Remove dep on vm-shim.

---

lib/shared_state.js

It's technically possible for us to return 'undefined' from .get, when the state
array has only 1 value and the requested time is identical to that tuple's time.
This is not likely the cause of #3, but is certainly related.

Fixing a terribly obscure edge case in state.

---

lib/promise.js
lib/state_machine.js

There's only 1 caller, this pattern of using Promise is mostly deprecated, so let's just inline it.

Remove Promise.defer.

---

client/modules/module_ticker.js

Filtered results are never captured or used.

Remove unneeded filter call.

---

server/modules/module_library.js

The current strategy fails when chicago-brick is used as an npm dep. Instead, do something that works, but is also hacky.

Change way we init fading.

---

server/modules/module_def.js

This fixes the issue of printing EventEmitter internals and all the module source code every time the layout changes.

Add custom inspect impl for module defs

---

bin/start_2x2_clients.sh

i noticed that things are wacky on macs with newer versions of chrome (i have v49).
This isn't a problem on my linux box (chrome v49).

Fix the sizing and positioning for the 2x2 client on macs.

---

.jshintignore
.jshintrc
lib/.jshintrc
lib/assert.js
lib/fake_require.js
lib/geometry.js
lib/promise.js
lib/rectangle.js
lib/shared_state.js
package.json

Run just a single jshint across entire repo (excluding node_modules).
This will catch things missed before (e.g., ```lib/```) and is still faster
because of the single ```npm run ...``` command.
PR also fixes a few jshint errors in ```lib/``` and removes the unused ```precommit-hook``` dev dependency (```pre-commit``` is sufficient for running basic npm scripts before commit).

Streamline jshint checking and make everything jshint clean.

---

server/server.js
server/webapp.js

With this patch, chicago-brick can be run from a project that includes chicago-brick as a dep in package.json with just an extra --node_modules_dir flag.
fixes #74

Add a flag for the node_modules dir.

---

config/demo-playlist.json

This demonstrates the slideshow youtube playlist loader.

Add cta module to chicago-brick.

---

server/modules/module_def.js
server/webapp.js

Without this change, we can technically require other files, but those files can't expose any symbols, which is totally useless!
Multi-file modules are 100% working after this, but I think there's only 1 last wonky bit in the server before we are really done.

Allow files required by modules to export symbols.

---

server/modules/module_def.js

Prior to this CL, there was no way to hide an overridden module's title or author. Now, eliding these keys from the config will cause the title card to not show those fields.
Closes #56.

Fix title card.

---

bin/run_1x1.sh
bin/run_2x2.sh
bin/run_chev6.sh
package.json

New versions of node have built-in debugging now. We no longer need
node-inspector.

Use built-in node debugging.

---

client/network/network.js
server/network/network.js

socket.io 1.5 introduced a new way to pass query params in, which is incompatible
with the old way. Also, they changed the way namespaces work, so reverted to the
new internal name on the server.

Fix network.

---

client/modules/client_state_machine.js
client/modules/module.js

This fixes #145 entirely, and should address the slow regression of performance in clients introduced after the major sm refactoring in 2.0. This is a simple bug fix, with no API changes.

Fix client sm

---

demo_modules/chicago-brick-live/chicago-brick-live.js

This fixes an issue causing chicago-brick-live to not be able to run
with the (semi) recent changes to how client and server require's
are handled.

Update chicago-brick-live to use serverRequire for socket.io-client.

---

demo_modules/slideshow/fullscreen_display.js
demo_modules/slideshow/load_from_drive.js
demo_modules/slideshow/slideshow.js

Found a couple more bugs in the slideshow module. Turns out, you need to revoke your object urls after you are done with them, as their default lifetime is that of the `document`. Whoops! Also, we weren't cleaning up our surface. DOUBLE WHOOPS.

More slideshow fixes & debugging

---

client/modules/client_state_machine.js
lib/state_machine.js
server/modules/module_state_machine.js

Our eventual goal is to have some external system driving the state machines, rather than the state machines driving themselves to the next module. Part of this is recovering correctly when an error occurs. The current implementation of error handling forces each sm to know about how to recover. The new error handling allows other systems (such as parent sms) to be told when an error occurs and to tell that state machine to do something about it.
This actually fixes a potential bug that I hadn't considered before now where a single client sm might have gotten screwed up, but the wall wouldn't have advanced the whole wall to the next module. Now, we theoretically handle this correctly. I'm not sure if this even happened in practice, though.

Replace handleError API with errorlistener in sm.

---

client/modules/module.js
client/style.css
server/modules/layout_state_machine.js
server/modules/module_def.js
server/modules/module_library.js
server/modules/module_state_machine.js
server/modules/server_state_machine.js

I broke this when I removed the 'stop' event from before.
This fix:
- Removes the super-duper hacky '_faded_out' module, which was based on having 'solid' in your playlist and so seems like an unreasonable burden.
- Introduces a slightly less hacky '_empty' module, which atm has special-casing in a couple of places based on the name. I've added TODOs to make this better.
- Always adds and removes a container in the client, even for invalid modules.
- Forces a constant background color for the container, which means that the compositor in the browser has a little more work to do, but also means that folks don't (technically) have to clear the screen and can count on its being black. This makes transitions to invalid modules fade correctly.
- Fix a bug when we fadeout so that we begin the …

Fix layout fadeout.

---

server/control.js
server/modules/layout_state_machine.js
server/modules/module_state_machine.js
server/modules/module_ticker.js
server/modules/playlist_driver.js
server/modules/server_state_machine.js
server/server.js

This moves all of the logic for moving from one module to another, or one layout to another outside of the state machines themselves. This is pretty major change from the way that we've done all such transitions up to this point, and so this code should be treated very suspiciously. It finally allows us to have more complicated logic around how the playlist works, because rather than needing to encoding the understanding of the playlist format into the SMs, which is an encapsulation violation, we can stick all of that logic in an external 'playlist driver' that knows about how to understand the playlist format. Finally, we have a chance of making that driver able to change things based on time of day, some calendar-based schedule, or really, anything else, without having to modify the SMs …

Drive SMs according to the playlist.

---

demo_modules/wind/bin/fetch_forecast.sh
demo_modules/wind/bin/fetch_mapdata.sh

- Allow output dir to be specified on command line and use a real tmpdir.
- Make shell scripts more portable.

Get shell scripts ready for cron.

---

demo_modules/slideshow/falling_display.js
demo_modules/slideshow/fullscreen_display.js
demo_modules/slideshow/load_from_drive.js
demo_modules/slideshow/load_from_flickr.js
demo_modules/slideshow/load_from_youtube.js
demo_modules/slideshow/load_local.js
demo_modules/slideshow/slideshow.js
demo_modules/wind/forecast_grid.js
demo_modules/wind/particle_field.js
demo_modules/wind/vector_field.js
demo_modules/wind/wind.js
server/fake_require.js
server/modules/module_def.js

They already worked properly on the client, but the server only supported
package-relative imports. Here we add path rewiting on the server for relative
paths and update all uses of module-relative imports to do them with relative
paths instead.
First step to fixing #103.

Module-relative imports

---

package-lock.json
package.json
server/server.js

This does nothing by default. If use_https is set, this enables HTTPS for incoming client connections using the certificates in the certs/ directory. If require_client_cert is set, the server rejects any connections from clients not using a certificate trusted by the server.

Add flags to enable HTTPS and to require client certs.

---

client/config.js
client/surface/threejs_surface.js
demo_modules/particles/particles.js
demo_modules/threejs_test/threejs_test.js
package-lock.json
package.json

Update the dep, the client config mapping, threejs surface, and demos.
The three-full package includes lots of the utilities and extras used by the examples and demos, which should be useful for building new wall modules.
Tested locally with threejs_test module.

Replace three with three-full for a better threejs experience.

---

.gitignore

Certs should eventually be stored somewhere other than development boxes, but for the time being I'd like to keep them from being accidentally rolled into a commit.

Keeping the certs directory out of the repo.

---

package-lock.json
package.json

Besides bringing us up to date with head, this also adds some shiny new features. See https://socket.io/blog/socket-io-2-0-0/ for details.
This version also works with ES6-style module imports, which is a great long-term goal for our
work (though it's uncertain how feasible this is for all of the code...).

Upgrade socket.io to latest.

---

package-lock.json
package.json

Resolves #243 
The google-drive-sheets package was the source of most of our audit issues and we aren't actually using it.  We're already using the official google package.

Remove unused google-drive-sheets package and deal with other NPM audit results

---

demo_modules/split_modules_example/brick.json
demo_modules/split_modules_example/hello_world_client.js
demo_modules/split_modules_example/hello_world_server.js
server/modules/module_def.js
server/modules/module_library.js
server/modules/module_loader.js

This simplifies some of the upcoming es6 work due to differences in how
the browser and node import non-es6-compatible modules.
Also provided is an example of what such a module looks like. This
should get cleaner post es6-module support.

Support separate client/server modules.

---

client/modules/module.js
demo_modules/.jshintrc
demo_modules/wind/wind.js
server/modules/module.js
server/modules/module_def.js
server/modules/server_state_machine.js

- rm custom geometry per moduledef. Instead, just use the normal
wall geometry.
- rm old reference to moduledef.def. Since we now load code by import,
we don't need any source to live in the framework code.
- rm global wall geometry. This was useful when layouts had a custom
polygon, but these are long gone.

Remove remnants of layout geometry:

---

client/modules/module.js
client/style.css
client/title_card.js
demo_modules/balls/brick.json
demo_modules/big_image_carousel/big_image_carousel_client.js
demo_modules/chaos/brick.json
demo_modules/chicago-brick-live/brick.json
demo_modules/cosines/brick.json
demo_modules/gears/brick.json
demo_modules/merge_balls/brick.json
demo_modules/operational_tests/brick.json
demo_modules/p5_game_of_life/brick.json
demo_modules/slideshow/brick.json
demo_modules/slither/brick.json
demo_modules/solid/brick.json
server/modules/module_def.js
server/modules/module_loader.js

- Move title and author out of 'config' object and onto special 'credit' key, which makes it easier to support a more complex set of titles.
- Fix title overflowing by shrinking title text to fit.
- Fix random bug in big_image_carousel that I uncovered while I was here that caused the module to infinite loop.

Improve title & author

---

client/modules/module_test.js
client/network/network.js
demo_modules/chicago-brick-live/chicago-brick-live-server.js
demo_modules/slideshow/fullscreen_display_server.js
demo_modules/slideshow/slideshow_client.js
demo_modules/slideshow/slideshow_server.js
lib/module_player.js
lib/socket_wrapper.js
lib/socket_wrapper_test.js
server/network/network.js

This completely changes the way that per-module networking works.
Before, we relied on socket.io namespaces to ensure that no module could
accidentally communicate with another module that was running at the
same time. This worked, but had three major drawbacks:
1. Relied on internal, undocumented socket.io APIs to ensure proper
cleanup of namespace sockets.
2. Messages sent before receiver was ready were dropped, which required
modules to invent complicated mechanisms to ensure both server &
client were ready before communicating.
3. Initial handshake on namespace caused a noticeable CPU spike on the
client which dropped some frames.
This change addresses each of those concerns:
1. One socket is opened per server and client, avoiding the need for
cleanup.
2. Messages are always queued up …

Multiplex per-module network on a single connection

---

demo_modules/slideshow/fullscreen_display_server.js
server/network/network.js

- As a property, it was getting *copied* into the wrapped socket, which
freezes the set of clients to the ones that were originally set.
- Making it a function copies the definition of the function and
hence makes the list of clients dynamic and current.

Fix network.clients API.

---

server/webapp.js

- This fixes a weird bug where a custom module would be unable to depend
on a brick /lib file because of the lack of a consistent path to that
file.

Allow serving node_modules on /node_modules path.

---

demo_modules/slideshow/load_from_drive_server.js
server/network/network.js

According to https://github.com/websockets/ws#websocket-compression,
node has some issues when this is enabled. Turns out, socket.io enables
it by default. For even tiny binary messages (10KB) with a large number
of clients, I was seeing 4s delays in sending and receiving.

Disable perMessageDeflate.

---

client/index.html
client/surface/threejs_surface.js
client/util/time.js
demo_modules/operational_tests/threejs_test.js
karma.conf.js
package.json
server/modules/module.js
server/modules/serving.js
server/server.js
server/webapp.js

This is in preparation for splitting the server into a playlist part and a server part. Now, we don't need to do a whole separate glob in order to get at the module directories; rather, we just rely on the module definitions (which contain a root) to figure out the directories to serve..

Change module registration to happen more dynamically.

---

server/modules/module_ticker.js

In node, this now aborts execution of the process.

Catch any errors thrown in tick.

---

demo_modules/mandelbrot/mandelbrot.fs

Lower zoom levels use float implementation instead of double because it is much faster.
Higher zoom levels still use the emualted double precision but with several optimizations:
- The escape time algorithm is switched to a faster one.
- Added a periodity check to detect in-set values sooner.
- Most of frc operations that force non-optimized calcualtions are replaced with normal ops. A few crucial places (identified empirically) still use frc versions to preserve precision.
- x^2 and x+x ops use special fast implementation.
- Escape detection and color index calculation are switched to a slightly less precise but faster version.
The optimized double precision shader is ~4x faster (20 vs 5 FPS) when tested on Nvidia hardware.

Optimize the Mandelbrot fractal shader

---

demo_modules/slideshow/brick.json
demo_modules/slideshow/fullscreen_display_server.ts

- Sometimes, you want global content to refresh when it finishes.
- This was handled all wrongly before
- Now, we are smart about how we update this global content when it finishes on a client.
- Also, add a test module that references the cobra videos.

Fix global content refreshes

---

lib/module_player.ts

- Before, we disposed the module.
- However, this can make _some_ screens dispose and others not, which looks weird.
- Instead, forge ahead.

Change behavior of module prep timeouts

---

demo_modules/slideshow/load_local_client.ts

- When we are forced to split, read from the server only.

Fix splitting when using a local asset server

---

client/client.ts
client/modules/events.ts
client/modules/module.ts
server/modules/module.ts

- This allows both the client & the server to depend on it sanely.
- Still passes deno check
- Makes vscode happy.

Define the loadModule events in a separate file.

---

demo_modules/_template/brick.json
demo_modules/_template/template_client.ts
demo_modules/_template/template_server.ts
lib/inject.ts

I thought it would be nice to have a base module that contains the entirety of the API for contributors. Especially since the load functions look like they're being slurped and their arguments are being injected with reflection.
~~This doesn't work right now because `wallGeometry` is undefined in `willBeShownSoon`, but I wanted to get your initial feedback on the bones and see if this is a mergeable idea.~~
Also added some code to remove comments in the inject logic to fix the above error.

Add template module + make inject work with comments.

---

server/flags.ts
server/playlist/calendar/fetch.ts
server/playlist/calendar/parse.ts
server/playlist/calendar/state.ts
server/server.ts

We are having issues with the wall reliably switching back to the default playlist after scheduled events end.
I ended up reimplementing the strategy of how we maintain the state because the current one relies on long-lived timeouts and I was having a hard time figuring out what was going wrong.
The new implementation fetches events every minute. Separately there's a loop firing every 10s that diffs the current state of the wall against what it should look like and updates the state if necessary.
I've added this implementation behind a flag so that we can revert quickly in case of an issue. I tested this pretty extensively against the prod calendar locally, but it's not the same thing.

Rewrite calendar state tracking.

---

bin/run_1x1.sh
bin/start_2x2_clients.sh
bin/start_chev6_clients.sh
demo_modules/penrose_tiles/brick.json
demo_modules/penrose_tiles/constants.ts
demo_modules/penrose_tiles/penrose_tiles_client.ts
demo_modules/penrose_tiles/penrose_tiles_server.ts
demo_modules/penrose_tiles/tile.ts
package-lock.json

Creates a new `penrose_tiles` module with testonly set - I am hoping to be able to do a "live" test of this soon (next week maybe?) and need guidance as to how to do that. Also updates the run scripts to allow the user to set the `CHROME` env variable outside of the script.
Future work:
- some sort of constant zoom so we can go beyond 7 iterations without creating zillions of tiles
- some sort of animated transition between iterations

feat: add new penrose_tiles module with testonly=true; improve shell scripts a bit

---

demo_modules/slideshow/load_local_client.ts

Version 96 was failing with a 500 which prevents images from loading.

Fix mime ESM shim to latest.
