google/chicago-brick

demo_modules/balls/balls.js
demo_modules/codelab01_filled_canvas/codelab01_filled_canvas.js
demo_modules/genlock_test/genlock_test.js
demo_modules/hello_world/hello_world.js
demo_modules/memory_debug/memory_debug.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/p5_template/p5_template.js
demo_modules/p5_test/p5_test.js
demo_modules/particles/particles.js
demo_modules/registration/registration.js
demo_modules/shared_test/shared_test.js
demo_modules/threejs_test/threejs_test.js
demo_modules/tutorials/01_simplest_module/simple_module.js
demo_modules/tutorials/02_procedural_client/procedural_client.js
demo_modules/tutorials/03_colors/colors.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js

I've left the P5Sketch instances as they were and will tidy that up in a separate CL since I'm not sure how that will interact with P5.

Update all the demo modules with class goodness.  

---

_layouts/default.html
css/index.css
index.md

Adds basic styling to our page.
Pre-work for #28.

Add layout & nav bar

---

client/modules/client_state_machine.js
client/modules/module.js
client/modules/module_manager.js
client/modules/module_ticker.js

Encapsulates fade in/out, disposal, module instance method invocation/error reporting, and container management.

Refactor client module mgmt into a class.

---

api.md

Initial attempt at api docs.

---

_layouts/default.html

Fix nav links in docs

---

client/modules/client_state_machine.js
client/modules/module.js
client/modules/module_manager.js
client/title_card.js
client/util/info.js

Formalize title card as a backwards-compatible client API

---

server/modules/module_registry.js
server/modules/module_state_machine.js

Stop depending on memory-debug for layout transitions.

---

server/modules/client_control_state_machine.js

Classify the client_control_state_machine.

---

client/modules/client_state_machine.js
client/modules/module.js
client/modules/module_manager.js

I think this should fix #49, because we handle prepare -> prepare correctly now.

Fix bug in client sm & clean house

---

client/modules/client_state_machine.js
lib/state_machine.js
server/modules/client_control_state_machine.js
server/modules/layout_state_machine.js
server/modules/module_def.js
server/modules/module_library.js
server/modules/module_state_machine.js
server/modules/playlist_loader.js
server/modules/server_state_machine.js

Changes to a module in the current playlist will cause the module state machine to immediately attempt to display it. Fixes #45.

Implement Auto-Reloading of modules

---

server/modules/module_library.js
server/modules/playlist_loader.js

Fixes /status not allowing config reset in UI.

Reset library modules on playlist re-parse.

---

demo_modules/slideshow/slideshow.js

The original interface was too specific to the staticdisplaystrategy; namely, it
expected a draw to occur as soon as new content was chosen from the load
strategy. This isn't feasible when we might not want to show something
immediately or when we want to animate something. The init/draw pair is more
generally useful.

Rejigger clientdisplaystrategy to be more general.

---

demo_modules/chicago-brick-live/chicago-brick-live.js
extras/chicago-brick-live/editor-server/app/js/components/Editor-example-code.js
extras/chicago-brick-live/editor-server/app/js/components/Editor.js

New Code.org style Artist for simple drawing plus improved configuration and few bug fixes.

Chicago brick live updates

---

demo_modules/chicago-brick-live/chicago-brick-live.js
extras/chicago-brick-live/editor-server/app/js/components/Editor.js

Fixes a bug that causes the client code to get time=undefined when time is zero.
Plus a few minor updates to comment blocks and whitespace.

Chicago brick live fixes

---

package.json

Use a fork+patch to fix the lwip dep.

fix lwip dep temporarily

---

server/network/network.js

Remove this part of the config message.

---

demo_modules/balls/balls.js
demo_modules/chicago-brick-live/chicago-brick-live.js
demo_modules/codelab01_filled_canvas/codelab01_filled_canvas.js
demo_modules/genlock_test/genlock_test.js
demo_modules/hello_world/hello_world.js
demo_modules/memory_debug/memory_debug.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/p5_template/p5_template.js
demo_modules/p5_test/p5_test.js
demo_modules/particles/particles.js
demo_modules/registration/registration.js
demo_modules/shared_test/shared_test.js
demo_modules/slideshow/slideshow.js
demo_modules/solid/solid.js
demo_modules/threejs_test/threejs_test.js
demo_modules/tutorials/01_simplest_module/simplest_module.js
demo_modules/tutorials/02_procedural_client/procedural_client.js
demo_modules/tutorials/03_colors/colors.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js

require module_interface, and use that, rather than ServerModuleInterface and ClientModuleInterface.

Stop relying on some magic globals.

---

client/modules/module.js
client/title_card.js
demo_modules/.jshintrc
demo_modules/balls/balls.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/particles/particles.js
demo_modules/slideshow/slideshow.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js
server/modules/module_def.js

Cleanup globals

---

client/client.js
client/index.html
client/modules/module.js
demo_modules/.jshintrc
demo_modules/balls/balls.js
demo_modules/chicago-brick-live/chicago-brick-live.js
demo_modules/codelab01_filled_canvas/codelab01_filled_canvas.js
demo_modules/genlock_test/genlock_test.js
demo_modules/hello_world/hello_world.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/p5_template/p5_template.js
demo_modules/p5_test/p5_test.js
demo_modules/particles/particles.js
demo_modules/registration/registration.js
demo_modules/shared_test/shared_test.js
demo_modules/slideshow/slideshow.js
demo_modules/solid/solid.js
demo_modules/threejs_test/threejs_test.js
demo_modules/tutorials/02_procedural_client/procedural_client.js
demo_modules/tutorials/03_colors/colors.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js
lib/register.js
server/modules/module_def.js

Remove all exposedNodeModules from client & server (removing the need for fake_require entirely).
Next steps: somehow make per-instantiation globals requirejs compatible.

Continue to remove globals

---

client/modules/module.js

This simplifies the module instantiation and error handling.

Inline loadModule.

---

server/modules/module_state_machine.js

Fix module state machine bug.

---

client/modules/client_state_machine.js
client/modules/module.js
demo_modules/balls/balls.js
demo_modules/chicago-brick-live/chicago-brick-live.js
demo_modules/codelab01_filled_canvas/codelab01_filled_canvas.js
demo_modules/genlock_test/genlock_test.js
demo_modules/hello_world/hello_world.js
demo_modules/memory_debug/memory_debug.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/p5_template/p5_template.js
demo_modules/p5_test/p5_test.js
demo_modules/particles/particles.js
demo_modules/registration/registration.js
demo_modules/shared_test/shared_test.js
demo_modules/slideshow/slideshow.js
demo_modules/solid/solid.js
demo_modules/threejs_test/threejs_test.js
demo_modules/tutorials/02_procedural_client/procedural_client.js
demo_modules/tutorials/03_colors/colors.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js
lib/fake_require.js
server/modules/module_def.js
server/modules/server_state_machine.js

Remove implicit globals

---

demo_modules/slideshow/slideshow.js

Because we aren't sure who's going to init first, the client may miss the init
message. Fix this by having the client force the server to send the message
when the client is ready. Because we only listen for these messages once, we
are sure we never double-init.

Fix bug in the slideshow init sequence.

---

client/config.js
config/demo-playlist.json
demo_modules/slideshow/load_from_flickr.js
demo_modules/slideshow/slideshow.js
package.json

Yet another way to load images into the slideshow.

Add load-from-flickr strategy to slideshow.

---

demo_modules/slideshow/falling_display.js
demo_modules/slideshow/fullscreen_display.js
demo_modules/slideshow/interfaces.js
demo_modules/slideshow/load_from_youtube.js
demo_modules/slideshow/load_video.js
demo_modules/slideshow/slideshow.js

This will allow us to totally remove any custom modules that just do video playback w/ syncing.

Add syncing to slideshow module.

---

client/config.js
client/index.html
package.json

Remove leaflet dependency.

---

package.json

i'm moving these to our internal repo.

Remove deps not used by the open source release.

---

server/modules/server_state_machine.js

Upgrade server state machine to es6-style.

---

package.json

this will include the big_image_carousel module once that is submitted.

Bump version to 0.2.3.

---

demo_modules/slideshow/load_from_drive.js

At least, until we make a better one.

Remove retry strategy from drive.

---

demo_modules/big_image_carousel/big_image_carousel.js

Fix glaring performance issue with the big image sketch.  

---

client/client.js
client/modules/client_state_machine.js
client/monitoring/monitor.js
client/network/network.js
client/style.css
server/modules/client_control_state_machine.js
server/modules/layout_state_machine.js
server/modules/module_state_machine.js
server/modules/server_state_machine.js
server/monitoring/monitor.js
server/server.js

Renders monitors above the client surfaces. Very shiny. Enable with
--enable_monitoring on the server cmd-line & monitor=1 in the client.
Fixes #4.

New monitoring solution.

---

lib/.jshintrc

Don't need most of the globals anymore.

Cleanup jshint globals.

---

demo_modules/balls/balls.js
demo_modules/big_image_carousel/big_image_carousel.js
demo_modules/chicago-brick-live/chicago-brick-live.js
demo_modules/codelab01_filled_canvas/codelab01_filled_canvas.js
demo_modules/genlock_test/genlock_test.js
demo_modules/memory_debug/memory_debug.js
demo_modules/p5_game_of_life/p5_game_of_life.js
demo_modules/p5_template/p5_template.js
demo_modules/p5_test/p5_test.js
demo_modules/registration/registration.js
demo_modules/shared_test/shared_test.js
demo_modules/slideshow/slideshow.js
demo_modules/solid/solid.js
demo_modules/threejs_test/threejs_test.js
demo_modules/tutorials/02_procedural_client/procedural_client.js
demo_modules/tutorials/03_colors/colors.js
demo_modules/tutorials/04_stars/stars.js
demo_modules/tutorials/05_balls/balls.js

Recent versions of the software log errors when no return value is returned from willBeShownSoon. Fix modules that violate that contract.

Add return values to willBeShownSoon.

---

demo_modules/slideshow/fullscreen_display.js
demo_modules/slideshow/load_from_drive.js

Improvements for next incremental version of chicago-brick to slideshow module, which allows finer control over rendering & video support from drive.

Videos for slideshow

---

client/status/index.html
client/status/status.js
server/control.js
server/webapp.js

Fixes issue #155 
Also adds a reset playlist button.
This could look much nicer, but it does what it says on the tin.

Allow module takeover + playback, even if not in a playlist.

---

package.json

this includes the module takeover changes.

Bump version to 2.11

---

client/status/index.html
client/status/status.js

The google playlist has some modules that aren't in a playlist
and can't be played temporarily.  They can only be played indefinitely
since that makes a fake playlist and forces a server reload.

Update status page for more complex configs.

---

demo_modules/chaos/chaos.js

Adds more ES6 & fixes some wonky code I found while perusing the code.

Update chaos module

---

client/modules/client_state_machine.js
client/modules/module.js
client/modules/module_manager.js
server/control.js
server/modules/client_control_state_machine.js
server/modules/module.js
server/modules/module_def.js
server/modules/module_state_machine.js
server/modules/module_ticker.js
server/modules/server_state_machine.js

* Simplify state machine by removing 'stop'
* Others...

Refactoring in preparation for fixing playlist

---

server/modules/module_state_machine.js

This would happen if we ever re-used the same sm after a fadeToBlack.

Fix a bug in the modulesm where we'd stop listening to reloads.

---

client/monitoring/monitor.js
client/style.css

Always stick states on the bottom of each timeline.
Add labels to the timelines.
Strip 'State' from the end of the state names, because duh.

Improve monitoring UI

---

client/monitoring/monitor.js
client/style.css
server/modules/client_control_state_machine.js
server/modules/layout.js
server/modules/layout_state_machine.js
server/modules/module_state_machine.js
server/modules/playlist_loader.js
server/modules/server_state_machine.js

This is in preparation to being able to control the state machines via the names only.

Pass around the names rather than the modules

---

client/modules/module.js
client/modules/module_ticker.js
client/monitoring/monitor.js
client/style.css
lib/assert.js
server/modules/module_state_machine.js

1) Add stack traces to assertions to better track down issues.
2) Only auto-reload when the changed module is currently playing.
3) Add UI that shows the currently drawing modules to the client monitor.

Three cleanups

---

client/monitoring/monitor.js

When we move playlist timing outside of the state machines themselves, we'll want a monitoring display to track them. This is that timeline.

Add timeline for playlist events.

---

server/control.js
server/modules/playlist_driver.js
server/modules/playlist_loader.js

(second patch to update my email in the commits)

Update the control API and status page to work with newest code.

---

demo_modules/wind/color.js
demo_modules/wind/particle_field.js
demo_modules/wind/vector_field.js
demo_modules/wind/wind.js

In the process, I consolidated calculations of some of the bounds.

Wind: Add particles and make them tile properly on larger walls.

---

.gitignore
demo_modules/wind/bin/fetch_forecast.sh
demo_modules/wind/bin/fetch_mapdata.sh
demo_modules/wind/wind.js

Also switched to prefix paths so downloads are namespaced.

Wind: Use coasts instead of country boundaries.

---

package.json

This automates the process of updating the package.json version, tagging a release, and publishing the npm.
Dry Run: $ npm run release -- --dry-run
Release minor version: $ npm run release
Release major version: $ npm run release -- major

Set up release tooling.

---

server/control.js
server/modules/layout_state_machine.js
server/modules/module_state_machine.js
server/modules/playlist_driver.js
server/server.js

More changes to simplify the lsm with the eventual goal of killing it.

Simplify lsm

---

demo_modules/wind/mask.js
demo_modules/wind/vector_field.js
demo_modules/wind/wind.js

Limit vector field and particles to the virtual rectangle dimensions rather than scaling to the whole wall.

Wind: Fix scaling issues

---

package-lock.json
package.json

Update license description in package.json to match actual license of code

---

demo_modules/gears/brick.json
demo_modules/gears/gears.js

- Modernize code a bit
- Remove internal gears
- Add axles, so we can have some depth to the gears. Darken the back layer:

Improve gears

---

bin/run_1x1.sh
bin/run_2x2.sh
bin/run_chev6.sh

Also make the run scripts more consistent with each other.

Update run_* scripts so debug works with newer node.

---

client/util/info.js

This is some of our oldest code, and much of it is out of date. This PR removes some unused API from the location bar and also the not-correct-and-wrong bezel configuration.

Clean up client configuration.

---

client/config.js
demo_modules/slideshow/load_from_flickr.js
package-lock.json
package.json

This has been superceded by the internal URLSearchParams API.

rm querystring dep

---

package-lock.json
package.json
server/modules/playlist_driver.js

- express
- release-it
- googleapis
- random-js

Upgrade npm dependencies

---

demo_modules/balls/balls_client.js
demo_modules/balls/balls_server.js
demo_modules/gears/gears_server.js
demo_modules/slideshow/brick.json
lib/math/polygon2d.js
lib/math/polygon2d_test.js
lib/math/rectangle.js
lib/math/vector2d.js
lib/shared_state.js

This fixes a bunch of minor little nits that were annoying me about the demo modules.

Spruce up demos

---

demo_modules/big_image_carousel/brick.json
demo_modules/operational_tests/brick.json
demo_modules/slideshow/brick.json
server/modules/module_def.js
server/modules/module_library.js
server/modules/module_loader.js
server/modules/playlist_loader.js

Add ability to mark a module as excluded from the default __ALL__ collection

---

lib/shared_state.js

- This allows the state interpolation to interpolate among a changing
set of objects by using the key of an object as a unique ID for that
object.

Restore * functionality to object interpolator.

---

server/control.js
status/index.html
status/index.js
status/playlist_creator.js

- This resets the playlist back to the one that was initially loaded.
Remove dead code in server/control.

Add 'reset' command to status page.

---

server/control.js
status/client_controller.js
status/index.html
status/index.js
status/playlist_controller.js
status/playlist_creator.js

Add some neat features:
- Better snapshots
- Better durations
- Viewable module configs.

Improve status page usability

---

server/control.js
status/index.html
status/index.js
status/playlist_creator.js

Reverts google/chicago-brick#294

Revert "Add 'reset' command to status page."

---

demo_modules/slither/brick.json
demo_modules/slither/slither_client.js
demo_modules/slither/slither_server.js
lib/math/vector2d.js

Make the snakes slightly more alive by having their eyes move.
Also, speed up the performance of the module by over 2x by splitting the rendering paths into per-snake paths, which allows chrome to quickly clip the paths that aren't visible.

Improve slither

---

demo_modules/tiffany/tiffany_client.js
demo_modules/tiffany/tiffany_server.js
lib/math/polygon2d.js
lib/math/polygon2d_test.js

There were some bugs both in my 0.5 port and before. Fix 'em all to restore beautiful stained glass windows.

Fix tiffany

---

bin/run_1x1.sh
client/util/time.js
package-lock.json
package.json
server/control.js
server/network/network.js
server/network/peer.js
server/server.js
server/util/time.js
server/util/wall_geometry.js

- Upgrade several npm modules
- Remove use of clock-skew; it's no longer needed, as fancy time calculation isn't required.
- Remove use of process.hrtime in favor of more standard performance.now
- Remove some unused flags
- Refactor the wall geometry manipulation code to actually live in the wall geometry module, which significantly simplifies the API the module exposes.
- Remove some dead control code & change the way that the control network socket is created & used.
- Move peerjs initialization to its own file
- Update the run_1x1 script to open two chrome windows on boot: one for the client & one for the status page.

Misc fixes

---

server/control.js
server/modules/module.js
server/network/network.js
server/network/peer.js
server/playlist/playlist_driver.js
server/playlist/playlist_loader.js
server/server.js
status/index.js

- Refactor and comment code to better understand how it works and what is going on.

More Misc fixes

---

demo_modules/balls/balls_server.ts
demo_modules/mandelbrot/messages.ts
demo_modules/mandelbrot/palette.ts
lib/math/collision.ts
lib/math/collision_test.ts
lib/math/line2d.ts
lib/math/line2d_test.ts
lib/math/polygon2d.ts
lib/math/polygon2d_test.ts
lib/math/vector2d.ts

- Also, clean up mandelbrot a little.

Add standard collision detection routines

---

client/client.ts
demo_modules/mandelbrot/mandelbrot_server.ts
lib/module_player.ts
lib/websocket.ts
server/network/websocket.ts
server/playlist/playlist_driver.ts
server/util/serving.ts

- misc cleanups as a result of actually running on a real wall.

More fixes

---

demo_modules/matrix/matrix.ts
demo_modules/slideshow/brick.json
demo_modules/slideshow/client_interfaces.ts
demo_modules/slideshow/fullscreen_display_client.ts
demo_modules/slideshow/fullscreen_display_server.ts
demo_modules/slideshow/load_from_youtube_client.ts
demo_modules/slideshow/load_from_youtube_server.ts
demo_modules/slideshow/slideshow_client.ts
lib/rate_limit.ts
server/modules/module_ticker.ts
server/util/credentials.ts

- Make rate limit chill out a bit.
- Make the fullscreen slideshow not update content until it's faded in.
- Improve the look of matrix
- Improve some logging
- Make YouTube loading actually work

Even more fixes

---

demo_modules/merge_balls/ball.ts
demo_modules/merge_balls/merge_balls_client.ts
demo_modules/merge_balls/merge_balls_server.ts
lib/math/spatial_db.ts
lib/math/vector2d.ts

- Add a spatial db to reduce constants in O(N^2) collision checking.
- Use standard collision detection functions.
- Fix bug related to ball index & edge rendering
- Add splitting as a thing that can happen.

Make merge-balls faster and more interesting

---

demo_modules/merge_balls/ball.ts
demo_modules/merge_balls/merge_balls_client.ts
demo_modules/merge_balls/merge_balls_server.ts

Improve state-sending part of merge-balls:

---

demo_modules/sliced_cubes/brick.json
demo_modules/sliced_cubes/sliced_cubes.ts
demo_modules/sliced_cubes/sliced_cubes_client.ts
demo_modules/sliced_cubes/sliced_cubes_server.ts

Reworks sliced_cubes in TypeScript and using modern Three.js

Resurrects the sliced_cubes demo

---

demo_modules/shifting_shapes/brick.json
demo_modules/shifting_shapes/shifting_shapes.ts

./bin/run_1x1.sh -m shifting-shapes
https://user-images.githubusercontent.com/3860311/222574047-06453c72-1ac5-4d7d-bfaf-4c582ac8d7f6.mp4

"shifting shapes" module
